[package]
name = "triturus"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
delaunator = "1.0.2"
geo = "0.28.0"
rand = "0.8.5"
rayon = "1.9.0"
