[package]
name = "xenobalanus"
version = "0.1.4"
edition = "2021"

[lib]
name = "xenobalanus"

[dependencies]
delaunator = "1.0.2"
geo = "0.28.0"
geo-types = "0.7.13"
itertools = "0.12.1"
rand = "0.8.5"
rayon = "1.9.0"
statrs = "0.16.0"
